export const data = {
  across: {
    1: {
      clue: "(3,4)",
      answer: "asdasdf",
      row: 0,
      col: 0,
    },
    4: {
      clue: "(4)",
      answer: "asdf",
      row: 8,
      col: 0,
    },
    7: {
      clue: "(4)",
      answer: "asdf",
      row: 3,
      col: 2,
    },
    8: {
      clue: "(7)",
      answer: "asdfghj",
      row: 5,
      col: 2,
    },
    10: {
      clue: "(6)",
      answer: "asdfgh",
      row: 0,
      col: 4,
    },
    12: {
      clue: "(5)",
      answer: "asdfg",
      row: 8,
      col: 5,
    },
    13: {
      clue: "(5)",
      answer: "asdfg",
      row: 0,
      col: 6,
    },
    15: {
      clue: "(6)",
      answer: "asdfgh",
      row: 6,
      col: 7,
    },
    18: {
      clue: "(7)",
      answer: "asdfghj",
      row: 0,
      col: 9,
    },
    19: {
      clue: "(4)",
      answer: "asdf",
      row: 8,
      col: 9,
    },
    20: {
      clue: "(4)",
      answer: "asdf",
      row: 0,
      col: 11,
    },
    21: {
      clue: "(7)",
      answer: "asdfghj",
      row: 5,
      col: 11,
    },
  },
  down: {
    1: {
      clue: "(5)",
      answer: "asdfg",
      row: 0,
      col: 0,
    },
    2: {
      clue: "(5)",
      answer: "asdfg",
      row: 3,
      col: 0,
    },
    3: {
      clue: "(5)",
      answer: "asdfg",
      row: 5,
      col: 0,
    },
    5: {
      clue: "(8)",
      answer: "asdfghjk",
      row: 9,
      col: 0,
    },
    6: {
      clue: "(6)",
      answer: "asdfgh",
      row: 11,
      col: 0,
    },
    9: {
      clue: "(4)",
      answer: "asdf",
      row: 6,
      col: 2,
    },
    11: {
      clue: "(8)",
      answer: "asdfghjk",
      row: 3,
      col: 4,
    },
    13: {
      clue: "(6)",
      answer: "asdfgh",
      row: 0,
      col: 6,
    },
    14: {
      clue: "(4)",
      answer: "asdf",
      row: 4,
      col: 6,
    },
    15: {
      clue: "(5)",
      answer: "asdfg",
      row: 6,
      col: 7,
    },
    16: {
      clue: "(5)",
      answer: "asdfg",
      row: 8,
      col: 7,
    },
    17: {
      clue: "(5)",
      answer: "asdfg",
      row: 11,
      col: 7,
    },
  },
};
